# Javascript Node CircleCI 2.0 configuration file
version: 2
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
var_1: &cache_key yarn-cache-{{ checksum "yarn.lock" }}
var_2: &node_image
  docker:
      - image: circleci/node:8.10.0-browsers

jobs:

  test:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key

      - run: yarn install
      - run: yarn gulp ci
      - run: yarn format:check

      - save_cache:
          key: *cache_key
          paths:
            - node_modules
            - ~/.cache/yarn

  deploy:
    <<: *node_image
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: *cache_key

      - run: yarn install
      - run: yarn gulp deploy:github-builds

      - store_artifacts:
          path: dist

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master