# Javascript Node CircleCI 2.0 configuration file
version: 2
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
var_1: &cache_key npm-cache-{{ checksum "package-lock.json" }}
var_2: &node_image
  docker:
      - image: circleci/node:latest-browsers

jobs:

  test:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm ci
      - run: npm run gulp ci

      - save_cache:
          key: *cache_key
          paths:
            - node_modules
            - ~/.npm

  deploy:
    <<: *node_image
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: *cache_key

      - run: npm ci
      - run: npm run gulp deploy

      - store_artifacts:
          path: dist/releases

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master