# Javascript Node CircleCI 2.0 configuration file
version: 2
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
var_1: &cache_key npm-cache-{{ checksum "package-lock.json" }}
var_2: &node_image
  docker:
      - image: circleci/node:latest-browsers

jobs:
  build:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: sudo npm up -g npm && npm ci
      - run: npm run gulp ci:build

      - save_cache:
          key: *cache_key
          paths:
            - node_modules
            - ~/.npm

  lint:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm run gulp ci:lint

  test:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm run gulp ci:test

  deploy:
    <<: *node_image
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: *cache_key

      - run: sudo npm up -g npm && npm ci
      - run: npm run gulp deploy

      - store_artifacts:
          path: dist/releases

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master